name: CelSpace
version: '0.1'
main: cel.space.Main
api-version: '1.20'
authors:
  - Cel20
description: Cel20's Space Plugin
commands:
  celspace:
    description: Overall command for Celspace
    usage: /celspace <goto>
  clearrp:
    description: Clears Server-Set resource packs
    usage: /clearrp
  unload:
    description: Unload a world
    usage: /unload <worldname>