name: CelSpace
version: '0.1'
main: cel.space.Main
api-version: '1.20'
authors:
  - Cel20
description: Cel20's Space Plugin
commands:
  mars:
    description: Get to Mars
    usage: /mars
  rp1:
    description: Test of Resource Pack sending
    usage: /rp1
  clearrp:
    description: Clears your ressource packs
    usage: /clearrp
  celspace:
    description: Overall command for Celspace
    usage: /celspace <goto>
